# parameters configuration
mode: predict_gui
root: data/
predefined_dataset: MNIST
classes: ["normal", "abnormal"]
max_samples: null
batch_size: 32
num_workers: 1
device: cuda
lr: 1e-3
model_name: AE
in_chans: 1
input_height: 64
latent_dim: 256
loss_function_name: MSELoss
checkpoint_path: pretrained/MNIST_test_accuracy_0.9919/checkpoints/epoch=11-step=1787-val_loss=0.0039.ckpt
seed: 0
early_stopping: True
patience: 3
default_root_dir: save/
gpus: -1
precision: 32
max_epochs: 100
color_space: L # (8-bit pixels, black and white)
threshold: 0.013034395047437797
web_interface: True
examples:
  [
    "examples/MNIST/00000_7_abnormal.png",
    "examples/MNIST/00001_2_abnormal.png",
    "examples/MNIST/00002_1_abnormal.png",
    "examples/MNIST/00003_0_normal.png",
    "examples/MNIST/00004_4_abnormal.png",
    "examples/MNIST/00007_9_abnormal.png",
    "examples/MNIST/00011_6_abnormal.png",
    "examples/MNIST/00061_8_abnormal.png",
    "examples/MNIST/00433_5_abnormal.png",
    "examples/MNIST/00449_3_abnormal.png",
  ]
tuning_test: False
cpu_resources_per_trial: 1
gpu_resources_per_trial: 0.25
num_samples: -1

# transforms configuration
transforms_config:
  train:
    Resize:
      - 64
      - 64
    ToTensor:

  val:
    Resize:
      - 64
      - 64
    ToTensor:

  test:
    Resize:
      - 64
      - 64
    ToTensor:

  predict:
    Resize:
      - 64
      - 64
    ToTensor:

# target transforms configuration
target_transforms_config:
  train: null

  val: null

  test: null

  predict: null

# optimizers configuration
optimizers_config:
  Adam:
    betas:
      - 0.9
      - 0.999
    eps: 1e-08
    weight_decay: 0
    amsgrad: False

# learning rate schedulers configuration
lr_schedulers_config:
  CosineAnnealingLR:
    T_max: 10

# hyperparameter space configuration
hyperparameter_space_config:
  lr:
    uniform:
      lower: 1e-4
      upper: 1e-1

  max_epochs:
    randint:
      lower: 100
      upper: 500
